#!/bin/bash

# Exit on error
set -e

MOVIDIUS_RULES_FILE="/etc/udev/rules.d/80-movidius.rules"

if [ ! -e ${MOVIDIUS_RULES_FILE} ]; then
    echo "Adding udev rule: ${MOVIDIUS_RULES_FILE}."
    echo 'SUBSYSTEM=="usb", ATTRS{idVendor}=="03e7", MODE="0666"' | tee ${MOVIDIUS_RULES_FILE}
    udevadm control --reload-rules
    udevadm trigger
fi

exit 0
