#!/bin/bash

# Exit on error
set -e

MOVIDIUS_RULES_FILE="/etc/udev/rules.d/80-movidius.rules"

if [ -e ${MOVIDIUS_RULES_FILE} ]; then
    echo "Removing udev rule: ${MOVIDIUS_RULES_FILE}."
    rm -rf /etc/udev/rules.d/80-movidius.rules
    udevadm control --reload-rules
    udevadm trigger
fi

exit 0

