name: tii-depthai-ctrl-coverity

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverity:
    runs-on: depthai-ctrl-self-hosted-coverity
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.coverity
          push: false
          tags: depthai_ctrl_coverity:latest

      - name: Run coverity scan
        run: |
          docker run --rm \
          -e PROJECT_NAME=${{ github.event.repository.name }} \
          -v "$(pwd):/main_ws/src" \
          depthai_ctrl_coverity:latest

      - name: Update summary
        run: |
          cat cov-analyze-result.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload coverity scan results
        uses: actions/upload-artifact@v3
        with:
          name: coverity-html-report-${{ github.event.repository.name }}
          path: coverity-output
