name: tii-depthai-ctrl-coverity

on:
  repository_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverity:
    runs-on: depthai-ctrl-self-hosted-coverity
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.coverity
          push: false
          tags: dephai_ctrl_coverity:latest
      - name: Run coverity scan
        run:
          docker run --rm -e PROJECT_NAME=${{ github.event.repository.name }} dephai_ctrl_coverity:latest
